"""empty message

Revision ID: d0b3cabe77e1
Revises: 1b974f000233
Create Date: 2022-09-21 15:04:01.798245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b3cabe77e1'
down_revision = '1b974f000233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_description',
               existing_type=sa.String(length=500),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
